DSTEW-192: Add Pingdom IPs to ingress
Error: data value name nested level is greater than maximum supported nested level of 30

Instead of using --set or --set-string with a long list of IPs,
create a temp values file, then use the --values flag to load it